#pragma once
#include <string>
constexpr auto ALPHABET_SIZE = 26;
constexpr auto DICTIONARY_FILE = "C:\\Users\\Admin\\Desktop\\dict.txt";

using namespace std;

string ROTOR_1 = "EKMFLGDQVZNTOWYHXUSPAIBRCJ";
string ROTOR_1T = "Q";
string ROTOR_2 = "AJDKSIRUXBLHWTMCQGZNPYFVOE";
string ROTOR_2T = "E";
string ROTOR_3 = "BDFHJLCPRTXVZNYEIWGAKMUSQO";
string ROTOR_3T = "V";
string ROTOR_4 = "ESOVPZJAYQUIRHXLNFTGKDCMWB";
string ROTOR_4T = "J";
string ROTOR_5 = "VZBRGITYUPSDNHLXAWMJQOFECK";
string ROTOR_5T = "Z";
string ROTOR_6 = "JPGVOUMFYQBENHZRDKASXLICTW";
string ROTOR_6T = "ZM";
string ROTOR_7 = "NZJHGRCXMYSWBOUFAIVLPEKQDT";
string ROTOR_7T = "ZM";
string ROTOR_8 = "FKQHTLXOCBJSPDZRAMEWNIUYGV";
string ROTOR_8T = "ZM";

string REFLECTOR_BETA = "LEYJVCNIXWPBQMDRTAKZGFUHOS";
string REFLECTOR_GAMMA = "FSOKANUERHMBTIYCWLQPZXVGJD";
string REFLECTOR_A = "EJMZALYXVBWFCRQUONTSPIKHGD";
string REFLECTOR_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT";
string REFLECTOR_C = "FVPJIAOYEDRZXWGCTKUQSBNMHL";
string REFLECTOR_B_THIN = "ENKQAUYWJICOPBLMDXZVFTHRGS";
string REFLECTOR_C_THIN = "RDOBJNTKVEHMLFCWZAXGYIPSUQ";